---
kind: Certificate
apiVersion: certmanager.k8s.io/v1alpha1
metadata:
  name: owncloud
spec:
  secretName: owncloud-cert
  issuerRef:
    name: owncloud-rootca
    kind: ClusterIssuer
  dnsNames:
  - owncloud.kube
