---
apiVersion: v1
kind: Secret
metadata:
  name: portal-sk-ru-online-editor-secret
  namespace: online-platform
type: Opaque
data:
  DB_PWD: '' # пароль для БД сервиса Onlyoffice
  JWT_SECRET: '' # Определяет секретный ключ для валидации JSON веб-токена при запросе к ONLYOFFICE Docs. Используется в т.ч. для настройки интеграции owncloud-onlyoffice
  OO_SSL_DHPARAM: '' # ключ Диффи-Хеллмана для onlyoffice
  OO_SSL_CERT: '' # самоподписанный сертификат на 10 лет для onlyoffice
  OO_SSL_KEY: '' # Закрытый ключ самоподписанного сертификата
  OO_SSL_CSR: '' # Файл запроса сертификата. Нигде не используется. на память
  OWNCLOUD_PASSWORD: ''  # password для owncloud
  OWNCLOUD_EMAIL: '' # Логин для админского доступа в веб-интерфейс owncloud
  OWNCLOUD_DATABASE_PASSWORD: '' # пароль для БД сервиса owncloud
  MARIADB_ROOT_PASSWORD: '' # root пароль для БД сервиса owncloud
  REDIS_PASS: ''
