---
apiVersion: v1
kind: Secret
metadata:
  name: owncloud-edit-secret
  namespace: online-platform
type: Opaque
data:
  DB_PWD                    : 'YWRtaW4K' # пароль для БД сервиса Onlyoffice
  JWT_SECRET                : 'Y2xvc2VrZXkK' # Определяет секретный ключ для валидации JSON веб-токена при запросе к ONLYOFFICE Docs. Используется в т.ч. для настройки интеграции owncloud-onlyoffice
  OO_SSL_DHPARAM            : 'Y2xvc2VrZXkK' # ключ Диффи-Хеллмана для onlyoffice
  OO_SSL_CERT               : 'Y2xvc2VrZXkK' # самоподписанный сертификат на 10 лет для onlyoffice
  OO_SSL_KEY                : 'Y2xvc2VrZXkK' # Закрытый ключ самоподписанного сертификата
  OO_SSL_CSR                : 'Y3Nya2V5Cg==' # Файл запроса сертификата. Нигде не используется. на память
  OWNCLOUD_PASSWORD         : 'YWRtaW4K'  # password для owncloud
  OWNCLOUD_EMAIL            : 'YWRtaW4K' # Логин для админского доступа в веб-интерфейс owncloud
  OWNCLOUD_DATABASE_PASSWORD: 'YWRtaW4K' # пароль для БД сервиса owncloud
  MARIADB_ROOT_PASSWORD     : 'YWRtaW4K' # root пароль для БД сервиса owncloud
  REDIS_PASS                : 'YWRtaW4K'
