---
apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-sk-ru-online-editor-cm
  namespace: online-platform
data:
  DB_TYPE: 'postgres'
  DB_HOST: '10.10.10.10' # IP-адрес или имя хоста, на котором запущен сервер базы данных onlyoffice
  DB_PORT: '5432' # Номер порта сервера базы данных, на котором находится база данных onlyoffice
  DB_NAME: 'online_editor_onlyoffice' # Название базы данных сервиса onlyoffice
  DB_USER: 'online_editor_onlyoffice' # Имя пользователя базы данных сервиса onlyoffice
  JWT_ENABLED: 'true' # Управляет включением валидации посредством JSON веб-токена ONLYOFFICE Docs.По умолчанию задано значение true.
  MARIADB_USER: 'online_editor_owncloud' # Название базы данных сервиса DB
  MARIADB_DATABASE: 'online_editor_owncloud' # Имя пользователя базы данных сервиса DB
  OWNCLOUD_DATABASE_HOST: 'portal-sk-ru-online-editor-svc' # Хост, на котором запущен сервер базы данных owncloud
  OWNCLOUD_DATABASE_PORT_NUMBER: '3306' # Порт БД, на котором запущен сервер базы данных owncloud
  OWNCLOUD_DATABASE_USER: 'online_editor_owncloud' # Имя пользователя к которому будет подключаться owncloud
  OWNCLOUD_DATABASE_NAME: 'online_editor_owncloud' # Имя базы, с которой будет работать owncloud
  OWNCLOUD_HOST: 'online-editor.uat.sk.ru'
  REDIS_SERVER_HOST: 'portal-sk-ru-online-editor-svc' # Сервис Redis для onlyoffice
  REDIS_SERVER_PORT: '6379'
  SSL_CERTIFICATE_PATH: '/var/www/onlyoffice/Data/certs/tls-crt/tls.crt' # Путь к используемому SSL-сертификату onlyoffice. Выпущен на 10 лет
  SSL_KEY_PATH: '/var/www/onlyoffice/Data/certs/tls-key/tls.key' # Путь к закрытому ключу SSL-сертификата onlyoffice
  SSL_DHPARAM_PATH: '/var/www/onlyoffice/Data/certs/dhparam/dhparam.pem' # Путь к параметру Диффи-Хеллмана onlyoffice
  TZ: 'Europe/Moscow'
  USE_UNAUTHORIZED_STORAGE: 'true' # 
  MASTER: 'true'
  config: |
    databases 1
    maxmemory 50mb
    tcp-keepalive 600
